export const moods = [
  { value: '社死', emoji: '🤡', label: '社死', color: '#FF4500' },
  { value: '摸鱼', emoji: '🐟', label: '摸鱼才是生活真谛', color: '#40E0D0' },
  { value: '躺尸', emoji: '🛌', label: '躺尸待机', color: '#2F4F4F' },
  { value: '裂开', emoji: '💔', label: '服了，真的', color: '#A52A2A' },
  { value: ' 卷不动 ', emoji: '💤', label: '卷起来', color: '#D3D3D3' },
  { value: ' 社恐 ', emoji: '🙈', label: ' 社交不了一点 ', color: '#87CEEB' },
  { value: 'emo', emoji: '🌧️', label: '...', color: '#4682B4' },
  { value: ' 破防 ', emoji: '💧', label: ' 破防了 ', color: '#00BFFF' },
  { value: ' 上头 ', emoji: '🍻', label: '上头中', color: '#DC143C' },
  { value: ' 躺平 ', emoji: '🪑', label: '躺平', color: '#5F9EA0' },
  { value: ' 摆烂 ', emoji: '📺', label: '摆烂', color: '#696969' },
  { value: '内耗', emoji: '🌀', label: 'CPU 干烧了', color: '#8A2BE2' },
  { value: '吃土', emoji: '🥲', label: '吃土了', color: '#D2691E' },
  { value: '发疯', emoji: '🤪', label: '精神状态良好', color: '#FF1493' },
  { value: '打工人', emoji: '🧱', label: '搬砖 ing', color: '#708090' },
  { value: '早八', emoji: '⏰', label: '人走魂还在', color: '#FFD700' },
  { value: '干饭', emoji: '🍚', label: '天大地大吃饭最大', color: '#FF8C00' },
  { value: '暴富', emoji: '💰', label: '准备暴富', color: '#32CD32' },
  { value: '水逆', emoji: '☄️', label: '诸事不宜', color: '#4682B4' },
  { value: '已读不回', emoji: '👻', label: '不要烦我', color: '#778899' },
  { value: '退退退', emoji: '🙅‍♂️', label: '霉运走开', color: '#FF6347' },
];